# -*- coding: utf-8 -*-
"""pinguin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kTlbQzMoLUyTgJQ62gxtiRU5bMygMgvP
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/dataset/penguins_size.csv')

df.head(10)

df.isna().sum()

